note
	description: "Root class for this application."
	author: "Generated by the Vision Application Wizard."
	date: "$Date: 2020/11/3 21:42:52 $"
	revision: "1.1.1"

class
	RPI_VIEWER

inherit

    JJ_APPLICATION
        redefine
--        	prepare,
			target_anchor,
            window_anchor
        end

create
	make_and_launch

feature {NONE} -- Initialization

--	prepare
--			-- Prepare the application by setting up `main_window'
--			-- and creating the `target', which is a {PI_4_CONTROLLER}.
--		do
--			Precursor
--			first_window.set_target (create {RPI})
--		end

feature {NONE} -- Implementation

feature {NONE} -- Implementation (anchors)

	target_anchor: RPI
			-- Anchor for features using nodes.
			-- Not to be called; just used to anchor types.
			-- Declared as a feature to avoid adding an attribute.
		require else
			not_callable: False
		do
			check
				do_not_call: False then
					-- Because give no info; simply used as anchor.
			end
		end

	window_anchor: VIEWER_MAIN_WINDOW
			-- Anchor for the type of `first_window'
			-- Not to be called; just used to anchor types.
			-- Declared as a feature to avoid adding an attribute.
		require else
			not_callable: False
		do
			check
				do_not_call: False then
					-- Because give no info; simply used as anchor.
			end
		end

end
